dist: bionic

env:
  global:
    - REPO=dedicatted03/kfs
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

stages:
- name: docker-build
  if: env(ONLY_BUILD) = true
- name: docker-run
  if: env(ONLY_RUN) = true

#git:
#  quiet: true

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'

jobs:
  include:
    - stage: docker-build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker build -f Dockerfile -t $REPO:$COMMIT .
      - docker images
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker images
      - docker push $REPO
    - stage: docker-run
      script:
      - docker run -it --privileged --name kfs --rm $REPO /bin/bash -c "/workdir/kfs.sh"

# blocklist
#branches:
#  except:
#  - master

# safelist
branches:
  only:
  - master

notifications:
  slack: testteam-c246404:XmuGaN04PZBk7IyJfhVTKSlj
