dist: bionic

env:
  global:
    - REPO=dedicatted03/kfs
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

#git:
#  quiet: true

jobs:
  include:
    - stage: build docker image and push to registry
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker build -f Dockerfile -t $REPO:$COMMIT .
      - docker images
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker images
      - docker push $REPO

notifications:
  slack: testteam-c246404:XmuGaN04PZBk7IyJfhVTKSlj
